### PR TITLE
Add constructor tests for FileCreateRequest

### PR DESCRIPTION
**Pull request by Ariho-Seth**
### Summary
Constructor tests for the **FileCreateRequest** Record were added in the **ProtocolLayerDataCreationTests** class 
A new test method i.e **testFileCreateRequestCreation** was added in the  **ProtocolLayerDataCreationTests**  class that implements all the needed tests for the **FileCreateRequest** record
### Issue Link
https://github.com/OpenElements/hedera-enterprise/issues/4
### Issue Number
#4

### CODE REVIEW

**Comment by Ndacyayisenga-droid** [comment]
@Ariho-Seth I would suggest you always run tests locally before a PR

**Comment by Ariho-Seth** [comment]
Something wrong happened @Ndacyayisenga-droid ?
I actually did the test and it ran successfully !!!

**Comment by Ariho-Seth** [comment]
Hello @Ndacyayisenga-droid , i think the PR is now good to go

**Comment by Ndacyayisenga-droid** [comment]
> Hello @Ndacyayisenga-droid , i think the PR is now good to go

@Ariho-Seth LGTM

**Comment by Ndacyayisenga-droid** [comment]
@Ariho-Seth please you commited more files than you were supposed to

**Comment by Ariho-Seth** [comment]
There is a small issue that was raised, on removing un used imports in those particular files , so they are the ones i removed and commited

**Comment by hendrikebbers** [comment]
@Ariho-Seth looks like you tried to use NPM / NODE in the project. Since this is a java project NPM and NODE are wrong. They are for JavaScript.
If you just delete the `package-lock.json` file and the `node_modules` folder (both in root) all should be good for that topic.
Once that is done I will have a look at your changes.

**Comment by Ariho-Seth** [comment]
Ohhh Yeah sure, I had some JS repo i was working with, i think somehow intermixed the commands
But I've worked on it 
I think its now good to go

**Review by hendrikebbers — APPROVED** [review]

**Comment by Ndacyayisenga-droid** [comment]
Thanks for working on this @Ariho-Seth

**Pull request merged**
