### PR TITLE
Implement MirrorNodeClient.queryTransaction

### PR DESCRIPTION
**Pull request by Ariho-Seth**
The `Optional<TransactionInfo> queryTransaction` method was expanded by using the `objectMapper` to convert the Json data from the API call into a `TransactionInfo` Object
The the **TrasactioInfo** class was also expanded to an Object containing fields identical to the Json data returned from the API call

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Hey @Ariho-Seth I think we should solve this differently. By adding jackson to the base module all module will depend on it. While that is great (and the correct solution) for Spring it is wrong for Microprofile or JakartaEE. Based on that I do not want to have any JSON lib specific code in the base module. https://github.com/OpenElements/hedera-enterprise/blob/main/hedera-microprofile/src/main/java/com/openelements/hedera/microprofile/implementation/ContractVerificationClientImpl.java shows already an example in that Microprofile uses the jakarta.json api. Do you understand my concerns?

**Comment by hendrikebbers** [comment]
@Ariho-Seth can you check if you can setup GitHub Sponsoring? You contribute a lot and I would like to give something back.

**Comment by Ariho-Seth** [comment]
> Hey @Ariho-Seth I think we should solve this differently. By adding jackson to the base module all module will depend on it. While that is great (and the correct solution) for Spring it is wrong for Microprofile or JakartaEE. Based on that I do not want to have any JSON lib specific code in the base module. https://github.com/OpenElements/hedera-enterprise/blob/main/hedera-microprofile/src/main/java/com/openelements/hedera/microprofile/implementation/ContractVerificationClientImpl.java shows already an example in that Microprofile uses the jakarta.json api. Do you understand my concerns?

Hello @hendrikebbers, Can I have more clarity here?
DOes this mean that you want instead of using the Jackson Library in the **https://github.com/OpenElements/hedera-enterprise/blob/main/hedera-base/src/main/java/com/openelements/hedera/base/mirrornode/TransactionInfo.java**, I should use the Jakarta.Json api?

**Comment by Ariho-Seth** [comment]
> @Ariho-Seth can you check if you can setup GitHub Sponsoring? You contribute a lot and I would like to give something back.

I would highly appreciate this, though GitHub Sponsoring isn't supported in my country so far, 
Can we try another option if possible?

**Comment by hendrikebbers** [comment]
@Ariho-Seth regarding honoring your work with a sponsoring: Other method are sadly quite complexe since Open Elements always needs a valide invoice that is working for German tax departments. GitHub Sponsoring is supporting that. No clue about good other possibilities. If you have suggestions just say it.

**Comment by hendrikebbers** [comment]
@Ariho-Seth regaring JSON: What I'm saying is that in the base module there should be NO JSON dependency. Based on that we sadly can not use something as the jackson annotations in the record (since that would not be compatible with other JSON libs like the one of Jakarta). Everything JSON need to be done in the modules that are framework specific (like spring, JakartaEE, ...) Since the records are needed in base we sadly need to do the conversion from JSON to java objects "by hand" as it is done currently in master. Does that make sense?

**Comment by Ariho-Seth** [comment]
> @Ariho-Seth regaring JSON: What I'm saying is that in the base module there should be NO JSON dependency. Based on that we sadly can not use something as the jackson annotations in the record (since that would not be compatible with other JSON libs like the one of Jakarta). Everything JSON need to be done in the modules that are framework specific (like spring, JakartaEE, ...) Since the records are needed in base we sadly need to do the conversion from JSON to java objects "by hand" as it is done currently in master. Does that make sense?

Sure it makes sense, let me work on it and i will shre with you my progress. Thanks alot!

**Comment by Ariho-Seth** [comment]
> @Ariho-Seth regarding honoring your work with a sponsoring: Other method are sadly quite complexe since Open Elements always needs a valide invoice that is working for German tax departments. GitHub Sponsoring is supporting that. No clue about good other possibilities. If you have suggestions just say it.
I was suggesting whether we can use WISE, wise is a technol company that offers international money transfer services faster and easier across borders.
Tell me if you are okay with it !

**Comment by hendrikebbers** [comment]
@Ariho-Seth can you contact me on LinkedIn: https://www.linkedin.com/in/hendrik-ebbers/ We can than discuss that out of Github

**Comment by Ariho-Seth** [comment]
Hello @hendrikebbers, Ive followed that link and i can't be able to send you a message, maybe am not your 1st degree connection.
Here is mine profile too maybe you can accept my connection request then we can be able to start a conversation
https://www.linkedin.com/in/atwijukire-ariho-seth-4a7a38259/

**Pull request closed without merging**
